[supervisord]
nodaemon=true

[program:deepstream]
command=/bin/bash -c 'python3 deepstream.py "rtsp://${NVR_USERNAME}:${NVR_PASSWORD}@${NVR_IP}:${NVR_PORT}/cam/realmonitor?channel=1&subtype=1&tcp"'
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
environment=GST_DEBUG="uridecodebin:4,rtspsrc:4,decodebin:4",NVIDIA_DEBUG="1",NVDS_ENABLE_EVENT_MSG_CONSUMER="1"

[program:fastapi]
command=uvicorn api:app --host 0.0.0.0 --port 8701
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
