SuperAnimalConversionTables: null
Task: PorkAnalysis
TrainingFraction:
- 0.95
alphavalue: 0.7
batch_size: 2
bodyparts:
- Spine1
- Shoulder_left
- Shoulder_right
- Center
- Spine2
- Hip_left
- Hip_right
- Tail_base
colormap: plasma
corner2move2:
- 50
- 50
cropping: false
date: Dec10
default_augmenter: default
default_net_type: resnet_50
detector_batch_size: 1
detector_snapshotindex: -1
dotsize: 12
engine: pytorch
identity: null
iteration: 0
move2corner: true
multianimalproject: false
numframes2pick: 25
pcutoff: 0.1
project_path: /home/engrkhan/visionpipe/src/deep_lab_cut/PorkAnalysis-WG-2025-12-10
scorer: WG
skeleton:
- - Spine1
  - Shoulder_left
- - Spine1
  - Shoulder_right
- - Spine1
  - Center
- - Spine1
  - Spine2
- - Spine1
  - Hip_left
- - Spine1
  - Hip_right
- - Spine1
  - Tail_base
- - Shoulder_left
  - Shoulder_right
- - Shoulder_left
  - Center
- - Shoulder_left
  - Spine2
- - Shoulder_left
  - Hip_left
- - Shoulder_left
  - Hip_right
- - Shoulder_left
  - Tail_base
- - Shoulder_right
  - Center
- - Shoulder_right
  - Spine2
- - Shoulder_right
  - Hip_left
- - Shoulder_right
  - Hip_right
- - Shoulder_right
  - Tail_base
- - Center
  - Spine2
- - Center
  - Hip_left
- - Center
  - Hip_right
- - Center
  - Tail_base
- - Spine2
  - Hip_left
- - Spine2
  - Hip_right
- - Spine2
  - Tail_base
- - Hip_left
  - Hip_right
- - Hip_left
  - Tail_base
- - Hip_right
  - Tail_base
skeleton_color: red
snapshotindex: -1
start: 0
stop: 1
video_sets:
  ? /home/nathaniel/Documents/GitHub/visionpipe/data/raw/deep_lab_cut/osfstorage-archive/DLC_tracking/videos/20210127_10-18-24_11-00-00.mp4
  : crop: 378, 1057, 239, 474
  ? /home/nathaniel/Documents/GitHub/visionpipe/data/raw/deep_lab_cut/osfstorage-archive/DLC_tracking/videos/20210127_12-00-00_12-58-30.mp4
  : crop: 378, 1057, 239, 474
  ? /home/nathaniel/Documents/GitHub/visionpipe/data/raw/deep_lab_cut/osfstorage-archive/DLC_tracking/videos/20210127_13-36-25_15-00-00.mp4
  : crop: 378, 1057, 239, 474
  ? /home/nathaniel/Documents/GitHub/visionpipe/data/raw/deep_lab_cut/osfstorage-archive/DLC_tracking/videos/20210127_15-00-00_15-28-25.mp4
  : crop: 378, 1057, 239, 474
  ? /home/nathaniel/Documents/GitHub/visionpipe/data/raw/deep_lab_cut/osfstorage-archive/DLC_tracking/videos/2021_02_03_12-00-00_12-34-04.mp4
  : crop: 378, 1057, 239, 474
  ? /home/nathaniel/Documents/GitHub/visionpipe/data/raw/deep_lab_cut/osfstorage-archive/DLC_tracking/videos/2021_02_03_14-00-00_14-43-53.mp4
  : crop: 378, 1057, 239, 474
  ? /home/nathaniel/Documents/GitHub/visionpipe/data/raw/deep_lab_cut/osfstorage-archive/DLC_tracking/videos/Eerder_groot_varken.mp4
  : crop: 378, 1057, 239, 474
  ? /home/nathaniel/Documents/GitHub/visionpipe/data/raw/deep_lab_cut/osfstorage-archive/DLC_tracking/videos/ExternDisk_ch1_20210127110000_20210127120000.mp4
  : crop: 378, 1057, 239, 474
  /home/nathaniel/Documents/GitHub/visionpipe/data/raw/deep_lab_cut/osfstorage-archive/DLC_tracking/videos/Groot_varken.mp4:
    crop: 378, 1057, 239, 474
  ? /home/nathaniel/Documents/GitHub/visionpipe/data/raw/deep_lab_cut/osfstorage-archive/DLC_tracking/videos/Klein_varken_1.mp4
  : crop: 378, 1057, 239, 474
  ? /home/nathaniel/Documents/GitHub/visionpipe/data/raw/deep_lab_cut/osfstorage-archive/DLC_tracking/videos/Klein_varken_2.mp4
  : crop: 378, 1057, 239, 474
  ? /home/nathaniel/Documents/GitHub/visionpipe/data/raw/deep_lab_cut/osfstorage-archive/DLC_tracking/videos/Middelklein_varken.mp4
  : crop: 378, 1057, 239, 474
  ? /home/nathaniel/Documents/GitHub/visionpipe/data/raw/deep_lab_cut/osfstorage-archive/DLC_tracking/videos/Middelmatig_varken.mp4
  : crop: 378, 1057, 239, 474
  ? /home/nathaniel/Documents/GitHub/visionpipe/data/raw/deep_lab_cut/osfstorage-archive/DLC_tracking/videos/Slachtrijp_varken.mp4
  : crop: 378, 1057, 239, 474
x1: 0
x2: 640
y1: 277
y2: 624
