services:
  #Our primairy database for storing images, videos and data from sensors 
  mongo:
    image: mongo
    container_name: PigEvalMongo
    #command: ["--replSet", "rs0"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}  # Ensure these are set in .env file
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
     - ../data/mongo-data:/data/db #A bind mount so that the data is stored beside docker-compose.yml
    #  - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    env_file: .env
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "mongosh", "--quiet", "--eval", "rs.status()"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 40s
  # mongo:
  #   image: mongo
  #   container_name: PigEvalMongo
  #   command: ["bash","/docker-entrypoint-initdb.d/mongo-init.sh"]
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #   volumes:
  #     - ../data/mongo-data:/data/db
  #     - ../data/mongo-config:/data/configdb
  #     - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  #   env_file: .env
  #   restart: unless-stopped

  # The frontend for users to interact with our system
  pig-sorting-streamlit:
    build:
      context: ./pig-sorting-streamlit
      dockerfile: Dockerfile
    # network_mode: "host"  # Use host networking for local development
    depends_on:
      - pig-sorting-api  # Ensures the API is up before Streamlit starts
    ports:
      - "8501:8501"
    restart: unless-stopped

  # The backend that will handle sending and reciving data from the database for the frontend(pig_sorting_streamlit).
  pig-sorting-api:
    build:
      context: ./pig-sorting-api
      dockerfile: Dockerfile
    # network_mode: "host"  # Use host networking for local development
    ports:
      - "8001:8001"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}  # Ensure these are set in your .env file
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ../data/images:/app/images  # Mount image folder where we store all images
      - ./pig-sorting-api/packages:/app/packages # Mount folder to download packages to so they persist across builds
    restart: unless-stopped
    depends_on:
      - mongo
      - model-deploy

  # For data annotation.
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    ports:
      - "8080:8080"
    volumes:
      - ../data/label-studio-data:/label-studio/data #contains the things from label studio
      - ../data:/label-studio/files # This will hold all outside data like images
    environment:
      - LABEL_STUDIO_USERNAME=${LABEL_STUDIO_USERNAME}
      - LABEL_STUDIO_PASSWORD=${LABEL_STUDIO_PASSWORD}
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files
      - LABEL_STUDIO_ALLOW_LOCAL_FILES_ACCESS=true # To allow exporting the images
    restart: unless-stopped

  #Primairy point for data ingestion, specifically for images, videos and sensor data
  data-intake:
    build:
      context: ./data-intake
      dockerfile: Dockerfile
    ports:
      - "8301:8301"
    environment:
      - NVR_USERNAME=${NVR_USERNAME}
      - NVR_PASSWORD=${NVR_PASSWORD}
      - NVR_IP=${NVR_IP}
      # - NVR_PORT=${NVR_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../data/images:/app/images
      - ../data/videos:/app/videos
      - ./data-intake/config.json:/app/config.json
    restart: unless-stopped


  # This container handles training different models
  model-training:
    build:
      context: ./model-training
      dockerfile: Dockerfile
    shm_size: '6gb' # needed to ensure enough space for training. May need to be increased if you are training larger models
    ports:
      - "8401:8401" 
    runtime: nvidia # In order to support gpu for training
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ../data/processed:/app/processed
      - ../models:/app/models
    restart: unless-stopped

  # One of the deployment containers that is suitable for testing trained models
  model-deploy:
    build:
      context: ./model-deploy
      dockerfile: Dockerfile
    ports:
      - "8601:8601" 
    runtime: nvidia # In order to support gpu for inference
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ../models:/app/models
    restart: unless-stopped

  # The second deployment container that can handle rtsp streams as a data input and does realtime inference
  deep-stream:
    build:
      context: ./deep-stream
      dockerfile: Dockerfile
    runtime: nvidia
    privileged: true  # Add this for hardware decoder access
    ipc: host        # Add this for shared memory
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video  # Add 'video' capability
      - NVR_USERNAME=${NVR_USERNAME}
      - NVR_PASSWORD=${NVR_PASSWORD}
      - NVR_IP=${NVR_IP}
      - NVR_PORT=${NVR_PORT}
    volumes:
      - ../models:/app/models
      - ./deep-stream/deepstream:/app/deepstream
      - ../data/videos:/app/videos  # Mount your video files
      - /dev:/dev  # Device access for hardware decoders
    ports:
      - "8701:8701"
      - "8554:8554"
    restart: unless-stopped

  # This will handle converting streams into different formats for compatibility between DeepStream and Streamlit
  data-stream:
    build:
      context: ./data-stream
      dockerfile: Dockerfile
    environment:
      - NVR_USERNAME=${NVR_USERNAME}
      - NVR_PASSWORD=${NVR_PASSWORD}
      - NVR_IP=${NVR_IP}
      # - NVR_PORT=${NVR_PORT}
    ports:
      - "8801:8801" 
    restart: unless-stopped
  